name: my_blood
description: A new Flutter project.
publish_to: "none"
version: 0.2.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  google_sign_in: ^4.5.0
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  provider: ^4.1.2
  flushbar: ^1.10.4
  font_awesome_flutter: ^8.8.1
  splashscreen: ^1.2.0
  bottom_navy_bar: ^5.4.0
  url_launcher: ^5.4.10
  maps_launcher: ^1.2.0
  extended_image: ^0.8.0
  intl: ^0.16.1
  expansion_tile_card: ^1.0.3
  simple_speed_dial: ^0.1.0
  search_cep: ^2.0.1+1
  firebase_storage: ^3.1.6
  image_picker: ^0.6.6+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0
  flutter_launcher_icons: ^0.7.5

flutter:
  uses-material-design: true
  assets:
    - lib/assets/

flutter_icons:
  ios: true
  android: true
  image_path_ios: "lib/assets/icon_complete.png"
  image_path_android: "lib/assets/icon_complete.png"
  adaptive_icon_background: "lib/assets/icon_background.png"
  adaptive_icon_foreground: "lib/assets/icon_foreground.png"
